name: Metrics (examples)
on:
  schedule:
    - cron: "0 2-23/4 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    if: "github.repository == 'Spafi/Spafi'"
    steps:

      # ======================================================================================
      # 🖼️ TEMPLATES
      # ======================================================================================

      # Classic template example
      - name: 📗 Classic template
        if: ${{ success() || failure() }}
        uses: Spafi/metrics@master
        with:
          filename: metrics.classic.svg
#           token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_lines: yes
          plugins_errors_fatal: ${{ github.repository == 'Spafi/Spafi' }}
          output_action: pull-request

#       # Repository template example, with some plugins enabled
#       # Notice how repository name is passed through "query" option
#       - name: 📘 Repository template
#         if: ${{ success() || failure() }}
#         uses: lowlighter/metrics@master
#         with:
#           template: repository
#           filename: metrics.repository.svg
#           token: ${{ secrets.METRICS_BOT_TOKEN }}
#           user: lowlighter
#           repo: metrics
#           plugin_lines: yes
#           plugin_followup: yes
#           plugin_projects: yes
#           plugin_projects_repositories: lowlighter/metrics/projects/1
#           plugins_errors_fatal: ${{ github.repository == 'Spafi/Spafi' }}
#           output_action: pull-request
